// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NubiChallengeApi.Data;

namespace NubiChallengeApi.Migrations
{
    [DbContext(typeof(NubiChallengeContext))]
    [Migration("20190801212719_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NubiChallengeApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Nombre");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new { Id = new Guid("a0000000-0000-0000-0000-000000000001"), Apellido = "Skywalker", Created = new DateTime(2019, 8, 1, 18, 27, 19, 365, DateTimeKind.Local), Email = "luke@mail.com", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Nombre = "Luke", Password = "luke123" },
                        new { Id = new Guid("a0000000-0000-0000-0000-000000000002"), Apellido = "Skywalker", Created = new DateTime(2019, 8, 1, 18, 27, 19, 365, DateTimeKind.Local), Email = "anakin@mail.com", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Nombre = "Anakin", Password = "anakin123" },
                        new { Id = new Guid("a0000000-0000-0000-0000-000000000003"), Apellido = "Kenobi", Created = new DateTime(2019, 8, 1, 18, 27, 19, 365, DateTimeKind.Local), Email = "obi-wan@mail.com", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Nombre = "Obi-Wan", Password = "obi-wan123" },
                        new { Id = new Guid("a0000000-0000-0000-0000-000000000004"), Apellido = "Skywalker", Created = new DateTime(2019, 8, 1, 18, 27, 19, 365, DateTimeKind.Local), Email = "leia@mail.com", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Nombre = "Leia", Password = "leia123" },
                        new { Id = new Guid("a0000000-0000-0000-0000-000000000005"), Apellido = "Solo", Created = new DateTime(2019, 8, 1, 18, 27, 19, 365, DateTimeKind.Local), Email = "han@mail.com", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Nombre = "Han", Password = "han123" },
                        new { Id = new Guid("a0000000-0000-0000-0000-000000000006"), Apellido = "Ren", Created = new DateTime(2019, 8, 1, 18, 27, 19, 365, DateTimeKind.Local), Email = "kylo@mail.com", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Nombre = "Kylo", Password = "kylo123" },
                        new { Id = new Guid("a0000000-0000-0000-0000-000000000007"), Apellido = "Amidala", Created = new DateTime(2019, 8, 1, 18, 27, 19, 365, DateTimeKind.Local), Email = "padme@mail.com", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Nombre = "Padme", Password = "padme123" },
                        new { Id = new Guid("a0000000-0000-0000-0000-000000000008"), Apellido = "Jinn", Created = new DateTime(2019, 8, 1, 18, 27, 19, 365, DateTimeKind.Local), Email = "qui-gon@mail.com", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Nombre = "Qui-Gon", Password = "qui-gon123" },
                        new { Id = new Guid("a0000000-0000-0000-0000-000000000009"), Apellido = "Windu", Created = new DateTime(2019, 8, 1, 18, 27, 19, 365, DateTimeKind.Local), Email = "mace@mail.com", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Nombre = "Mace", Password = "mace123" },
                        new { Id = new Guid("a0000000-0000-0000-0000-000000000010"), Apellido = "Maul", Created = new DateTime(2019, 8, 1, 18, 27, 19, 365, DateTimeKind.Local), Email = "darth@mail.com", Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Nombre = "Darth", Password = "darth123" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
